[package]
name = "totp-rs"
version = "5.6.0"
authors = ["Cleo Rebert <cleo.rebert@gmail.com>"]
edition = { workspace = true }
readme = "README.md"
license = "MIT"
description = "RFC-compliant TOTP implementation with ease of use as a goal and additionnal QoL features."
repository = "https://github.com/constantoine/totp-rs"
homepage = "https://github.com/constantoine/totp-rs"
keywords = ["authentication", "2fa", "totp", "hmac", "otp"]
categories = ["authentication", "web-programming"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
otpauth = ["url", "urlencoding"]
qr = ["dep:qrcodegen-image", "otpauth"]
serde_support = ["serde"]
gen_secret = ["rand"]
steam = []

[dependencies]
base32 = { workspace = true }
constant_time_eq = { workspace = true }
hmac = { workspace = true }
qrcodegen-image = { optional = true, workspace = true }
rand = { optional = true, workspace = true, features = ["std_rng", "std"] }
serde = { optional = true, workspace = true, features = ["derive"] }
sha1 = { workspace = true }
sha2 = { workspace = true }
urlencoding = { optional = true, workspace = true }
url = { optional = true, workspace = true }
zeroize = { optional = true, workspace = true }
