services:
  valkey:
    image: valkey/valkey:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - valkeydata:/data
      
  backend:
    build: .
    command: /app/c3a-worker
    ports:
      - "8072:8072"
    volumes:
      - ./logs:/logs
    depends_on:
      valkey:
        condition: service_healthy

volumes:
  valkeydata:
