[package]
name = "c3a-common"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20poly1305 = "0.10"
pqc_dilithium = { optional = true, git = "https://github.com/markcda/pqc_dilithium.git", features = [
  "mode5",
] }
rand = "0.8.5"
rand_chacha = "0.3"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["worker-types", "app-server-types", "app-client-types", "pqc-utils"]
worker-types = []
app-server-types = []
app-client-types = []
pqc-utils = ["dep:pqc_dilithium"]
