[application]
name = "c3a"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "C3A Authority"

[web.watcher]
watch_path = ["src", "public"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []
