[package]
name = "c3a-worker"
version = "0.1.0"
edition = "2021"
authors = ["Klimenty Titov <aclo.create@gmail.com>"]

[dependencies]
cc-server-kit = { git = "https://github.com/markcda/cc-server-kit.git", default-features = false, features = ["http3", "oapi", "utils", "otel"] }
tokio = { version = "1" }
