project_name: c3a-worker
version: 4
langs:
  - rust
targets:
  - arch: x86_64
    os: Linux
    os_derivative: any
    os_version:
      type: no
cache_files:
  - .git
  - Cargo.lock
  - target
artifacts:
  - target/release/c3a-worker
variables: []
place_artifacts_into_project_root:
  - from: target/release/c3a-worker
    to: c3a-worker
pipelines:
  - title: build
    desc: Got from `Default Rust Pipeline`.
    info: rust-default@0.1.0
    tags:
      - rust
      - cargo
      - upx
    default: true
    actions:
      - title: Lint
        desc: Got from `Cargo Clippy`.
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy
              ignore_fails: false
              show_success_output: true
              show_bash_c: true
      - title: Format
        desc: ""
        info: cargo-fmt@0.1.0
        tags: []
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
      - title: Build
        desc: Got from `Cargo Build (Release)`. Build the Rust project with Cargo default settings in release mode
        info: cargo-rel@0.1
        tags:
          - rust
          - cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo build --release
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
      - title: Clear Test KvDb Data
        desc: ""
        info: clear-test-kv-data@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: custom
          bash_c: rm -rf .fjall_data
          ignore_fails: false
          show_success_output: false
          show_bash_c: true
          only_when_fresh: false
          daemon: false
      - title: Test
        desc: Получено из `Start C3A`.
        info: c3a-start@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: test
          command:
            bash_c: RUST_BACKTRACE=1 cargo test
            ignore_fails: false
            show_success_output: true
            show_bash_c: true
            only_when_fresh: false
          success_when_found: "test result: ok."
      - title: Compress
        desc: Got from `UPX Compress`. Compress the binary file with UPX.
        info: upx-compress@0.1.0
        tags:
          - upx
        action:
          type: post_build
          supported_langs:
            - any
          commands:
            - bash_c: upx <artifact>
              ignore_fails: false
              show_success_output: false
              show_bash_c: false
              placeholders:
                - <artifact>
              replacements:
                - group:
                    - from: <artifact>
                      to:
                        title: target/release/c3a-worker
                        is_secret: false
                        value:
                          type: plain
                          value: target/release/c3a-worker
  - title: deploy
    desc: Got from `Default Rust Pipeline`.
    info: rust-default@0.1.0
    tags:
      - rust
      - cargo
      - upx
    default: false
    actions:
      - title: Lint
        desc: Got from `Cargo Clippy`.
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy
              ignore_fails: false
              show_success_output: true
              show_bash_c: true
      - title: Build
        desc: Got from `Cargo Build (Release)`. Build the Rust project with Cargo default settings in release mode
        info: cargo-rel@0.1
        tags:
          - rust
          - cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo build --release
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
      - title: Compress
        desc: Got from `UPX Compress`. Compress the binary file with UPX.
        info: upx-compress@0.1.0
        tags:
          - upx
        action:
          type: post_build
          supported_langs:
            - any
          commands:
            - bash_c: upx <artifact>
              ignore_fails: false
              show_success_output: false
              show_bash_c: false
              placeholders:
                - <artifact>
              replacements:
                - group:
                    - from: <artifact>
                      to:
                        title: target/release/c3a-worker
                        is_secret: false
                        value:
                          type: plain
                          value: target/release/c3a-worker
      - title: Start C3A
        desc: ""
        info: c3a-start@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: observe
          command:
            bash_c: ./target/release/c3a-worker
            ignore_fails: true
            show_success_output: true
            show_bash_c: false
            only_when_fresh: false
