[package]
name = "u2f-app"
version = "0.2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>"]
edition = "2024"

[dependencies]
lazy_static = "1.5"
rocket = { version = "0.5", features = ["tls", "json", "secrets"] }
serde = { workspace = true }
serde_json = { workspace = true }
u2f = { workspace = true, features = ["rand"] }
